<?php
// languages.php
return [
    'en' => [
        'home' => 'Home',
        'discover' => 'Discover',
        'hotels' => 'Hotels',
        'experiences' => 'Experiences',
        'itinerary' => 'Itinerary',
        'about_project' => 'About Project',
        'login_register' => 'Login / Register',
        'top_attractions' => 'Top Istanbul Attractions',
        'top_attractions_desc' => 'Discover the most famous and beautiful places in the city',
        'view_all' => 'View All',
        'search_placeholder' => 'Search attractions, hotels, restaurants or experiences...',
        'popular_suggestions' => 'Popular Suggestions:',
        'historical_places' => 'Historical Places',
        'hotels_accommodation' => 'Hotels & Accommodation',
        'restaurants_cafes' => 'Restaurants & Cafes',
        'undiscovered_areas' => 'Undiscovered Areas',
        'newsletter_title' => 'Ready to discover Istanbul? 🇹🇷',
        'newsletter_desc' => 'Get the latest travel guides, discounts and special experiences with our newsletter',
        'subscribe' => 'Subscribe',
        'privacy_note' => 'By subscribing, you accept our <a href="#">privacy policy</a>',
        'ai_assistant' => 'Istanbul AI Assistant 🇹🇷',
        'ai_assistant_desc' => 'Online • Instant Response',
        'chat_placeholder' => 'Ask your question...',
        'footer_discover' => 'Discover',
        'footer_guides' => 'Guides',
        'footer_support' => 'Support',
        'footer_mobile_app' => 'Mobile App',
        'copyright' => '© {year} Istanbul Guide 🇹🇷. All rights reserved.',
        'disclaimer' => 'This is a demo project and not associated with real Istanbul tourism.',
        // ... ادامه ترجمه‌ها
    ],
    
    'tr' => [
        'home' => 'Ana Sayfa',
        'discover' => 'Keşfet',
        'hotels' => 'Otel',
        'experiences' => 'Deneyimler',
        'itinerary' => 'Seyahat Planı',
        'about_project' => 'Proje Hakkında',
        'login_register' => 'Giriş / Kayıt',
        'top_attractions' => 'İstanbul\'un En İyi Gezilecek Yerleri',
        'top_attractions_desc' => 'Şehrin en ünlü ve en güzel yerlerini keşfedin',
        'view_all' => 'Hepsini Gör',
        'search_placeholder' => 'Gezi yerleri, oteller, restoranlar veya deneyimleri ara...',
        'popular_suggestions' => 'Popüler Öneriler:',
        'historical_places' => 'Tarihi Yerler',
        'hotels_accommodation' => 'Otel ve Konaklama',
        'restaurants_cafes' => 'Restoran ve Kafeler',
        'undiscovered_areas' => 'Keşfedilmemiş Bölgeler',
        'newsletter_title' => 'İstanbul\'u keşfetmeye hazır mısınız? 🇹🇷',
        'newsletter_desc' => 'Bültenimizle en son seyahat rehberlerini, indirimleri ve özel deneyimleri alın',
        'subscribe' => 'Abone Ol',
        'privacy_note' => 'Abone olarak <a href="#">gizlilik politikamızı</a> kabul etmiş olursunuz',
        'ai_assistant' => 'İstanbul AI Asistanı 🇹🇷',
        'ai_assistant_desc' => 'Çevrimiçi • Anında Yanıt',
        'chat_placeholder' => 'Sorunuzu sorun...',
        'footer_discover' => 'Keşfet',
        'footer_guides' => 'Rehberler',
        'footer_support' => 'Destek',
        'footer_mobile_app' => 'Mobil Uygulama',
        'copyright' => '© {year} Istanbul Guide 🇹🇷. Tüm hakları saklıdır.',
        'disclaimer' => 'Bu bir demo projesidir ve gerçek İstanbul turizmi ile ilişkili değildir.',
        // ... ادامه ترجمه‌ها
    ],
    
    'fa' => [
        'home' => 'خانه',
        'discover' => 'کشف‌کنید',
        'hotels' => 'اقامت',
        'experiences' => 'تجربه‌ها',
        'itinerary' => 'برنامه سفر',
        'about_project' => 'درباره پروژه',
        'login_register' => 'ورود / ثبت‌نام',
        'top_attractions' => 'جاذبه‌های برتر استانبول',
        'top_attractions_desc' => 'معروف‌ترین و دیدنی‌ترین مکان‌های شهر را کشف کنید',
        'view_all' => 'مشاهده همه',
        'search_placeholder' => 'جاذبه‌ها، هتل‌ها، رستوران‌ها یا تجربه‌ها را جستجو کنید...',
        'popular_suggestions' => 'پیشنهادهای پرطرفدار:',
        'historical_places' => 'جاذبه تاریخی',
        'hotels_accommodation' => 'هتل و اقامتگاه',
        'restaurants_cafes' => 'رستوران و کافه',
        'undiscovered_areas' => 'منطقه کشف‌نشده',
        'newsletter_title' => 'آماده کشف استانبول هستید؟ 🇹🇷',
        'newsletter_desc' => 'با خبرنامه ما، جدیدترین راهنمای سفر، تخفیف‌ها و تجربه‌های خاص را دریافت کنید',
        'subscribe' => 'عضویت',
        'privacy_note' => 'با عضویت، <a href="#">حریم خصوصی</a> را می‌پذیرید',
        'ai_assistant' => 'دستیار هوشمند استانبول 🇹🇷',
        'ai_assistant_desc' => 'آنلاین • پاسخ فوری',
        'chat_placeholder' => 'سوال خود را بپرسید...',
        'footer_discover' => 'کشف کنید',
        'footer_guides' => 'راهنماها',
        'footer_support' => 'پشتیبانی',
        'footer_mobile_app' => 'اپلیکیشن موبایل',
        'copyright' => '© {year} Istanbul Guide 🇹🇷. تمامی حقوق محفوظ است.',
        'disclaimer' => 'این پروژه یک پروژه نمایشی است و با استانبول‌گردی واقعی مرتبط نمی‌باشد.',
        // ... ادامه ترجمه‌ها
    ]
];